name: rigz
description: "Rigz is a Flutter app for smoothly browsing and buying PC parts."
version: 1.5.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.8
  palette_generator: ^0.3.3+6
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.8.0
  photo_view: ^0.15.0
  badges: ^3.1.2
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  slide_to_confirm: ^1.1.0
  animated_flip_counter: ^0.3.4

  #Backend
  decimal: ^3.2.1
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  flutter_neumorphic_plus: ^3.4.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Discount.png
    - lib/.env
